# Generated by Django 4.1 on 2023-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=100)),
                ('optionA', models.CharField(default='', max_length=28)),
                ('optionB', models.CharField(default='', max_length=28)),
                ('optionC', models.CharField(default='', max_length=28)),
                ('optionD', models.CharField(default='', max_length=28)),
                ('answer', models.CharField(default='', max_length=28)),
            ],
        ),
    ]
