# Generated by Django 4.1 on 2023-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(blank=True, to='home.topic'),
        ),
    ]
