# Generated by Django 4.1 on 2023-01-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='id',
            new_name='topicid',
        ),
    ]
